services:

  nginx:
    build:
      context: ./
      dockerfile: docker/nginx/Dockerfile
    restart: unless-stopped
    depends_on:
      - php
    ports:
      - "8008:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

  php:
    build:
      context: ./
      dockerfile: docker/php/Dockerfile
      args:
        ENV: development
    restart: unless-stopped
    volumes:
      - .:/var/www/html
      - ./docker/php/config/ini/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./docker/php/config/ini/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini

  database:
    image: postgres:14.5-alpine3.16
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "${DB_NAME}"
      POSTGRES_USER: "${DB_USERNAME}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - ./docker/database/init.db.sql:/docker-entrypoint-initdb.d/init.db.sql
